# Generated by Django 5.0.4 on 2026-05-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brand_banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/banners/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/logos/'),
        ),
    ]
