# Generated by Django 5.0.1 on 2024-01-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=100, null=True),
        ),
    ]
