# Generated by Django 5.0.4 on 2024-05-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='price_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
